name: 'Log to Pangea'
description: 'Write a new entry into Pangea Secure Audit Log'
branding: 
  icon: archive
  color: purple
inputs:
  text:
    description: 'Text to pass into the message field'
    required: true
  domain:
    description: 'Pangea Domain'
    required: true
  token:
    description: 'Pangea Token with access to Secure Audit Log Service'
    required: true
outputs:
  http_response:
    description: 'The result from the Pangea API'
runs:
  using: 'node20'
  main: 'dist/index.js'
